name: rescueiq

description: "RescueIQ - Smart Emergency First Aid Assistant"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  http: ^1.2.2
  sqflite: ^2.3.0
  image_picker: ^1.1.2
  geolocator: ^13.0.1
  geocoding: ^4.0.0
  sqflite_common_ffi: ^2.3.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.2
  path: ^1.9.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

  adaptive_icon_background: "#2563EB"
  adaptive_icon_foreground: "assets/icons/rescueiq_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
